name: reports

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  reports:
    runs-on: ubuntu-latest
    name: Generate coverage and test reports
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
        pip install -e .
        pytest --junitxml=.reports/junit/junit.xml --html=.reports/junit/report.html \
            --cov=tsk --cov-report xml:.reports/coverage/coverage.xml
        genbadge tests -i .reports/junit/junit.xml -o .reports/junit/badge.svg
        genbadge coverage -i .reports/coverage/coverage.xml -o .reports/coverage/badge.svg
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .reports
        git commit -m "automatically generated reports"
        git push